name: Deploy Function

on:
  push:
    paths:
      - 'supabase/functions/**'
      - '.github/workflows/deploy_functions.yml'
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy_functions:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_DEVELOP_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.SUPABASE_DEVELOP_PROJECT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy all edge functions to remote supabase
        run: supabase functions deploy --project-ref $PROJECT_ID
